package com.Ankiety_PZ.hibernate;
// Generated 2020-04-16 17:33:57 by Hibernate Tools 4.3.1



/**
 * Nagrody generated by hbm2java
 */
public class Nagrody  implements java.io.Serializable {


     private Integer id;
     private int liczbaPunktow;
     private String nazwa;
     private byte[] zdjecie;

    public Nagrody() {
    }

	
    public Nagrody(int liczbaPunktow, String nazwa) {
        this.liczbaPunktow = liczbaPunktow;
        this.nazwa = nazwa;
    }
    public Nagrody(int liczbaPunktow, String nazwa, byte[] zdjecie) {
       this.liczbaPunktow = liczbaPunktow;
       this.nazwa = nazwa;
       this.zdjecie = zdjecie;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getLiczbaPunktow() {
        return this.liczbaPunktow;
    }
    
    public void setLiczbaPunktow(int liczbaPunktow) {
        this.liczbaPunktow = liczbaPunktow;
    }
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }
    public byte[] getZdjecie() {
        return this.zdjecie;
    }
    
    public void setZdjecie(byte[] zdjecie) {
        this.zdjecie = zdjecie;
    }




}


