package com.Ankiety_PZ.hibernate;
// Generated 2020-04-16 17:33:57 by Hibernate Tools 4.3.1


import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import java.util.List;

/**
 * Nagrody generated by hbm2java
 */
public class Nagrody implements java.io.Serializable {


    private Integer idNagrody;
    private int liczbaPunktow;
    private String nazwa;
    private byte[] zdjecie;

    private List<Uzytkownicy> uzytkownicy;

    public Nagrody() {
    }


    public Nagrody(int liczbaPunktow, String nazwa) {
        this.liczbaPunktow = liczbaPunktow;
        this.nazwa = nazwa;
    }

    public Nagrody(int liczbaPunktow, String nazwa, byte[] zdjecie) {
        this.liczbaPunktow = liczbaPunktow;
        this.nazwa = nazwa;
        this.zdjecie = zdjecie;
    }

    public Integer getIdNagrody() {
        return this.idNagrody;
    }

    public void setIdNagrody(Integer id) {
        this.idNagrody = id;
    }

    public int getLiczbaPunktow() {
        return this.liczbaPunktow;
    }

    public void setLiczbaPunktow(int liczbaPunktow) {
        this.liczbaPunktow = liczbaPunktow;
    }

    public String getNazwa() {
        return this.nazwa;
    }

    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }

    public byte[] getZdjecie() {
        return this.zdjecie;
    }

    public void setZdjecie(byte[] zdjecie) {
        this.zdjecie = zdjecie;
    }

    @ManyToMany
    @JoinTable(name = "uzytkownicy_nagrody",
            joinColumns = {@JoinColumn(name = "idNagrody")},
            inverseJoinColumns = {@JoinColumn(name = "idUzytkownika")})
    public List<Uzytkownicy> getUzytkownicy() {
        return uzytkownicy;
    }

    public void setUzytkownicy(List<Uzytkownicy> uzytkownicy) {
        this.uzytkownicy = uzytkownicy;
    }

}


