package com.Ankiety_PZ.hibernate;
// Generated 2020-04-16 17:33:57 by Hibernate Tools 4.3.1



/**
 * Odpowiedzi generated by hbm2java
 */
public class Odpowiedzi  implements java.io.Serializable {


     private Integer id;
     private Pytania pytania;
     private String odpowiedz;

    public Odpowiedzi() {
    }

    public Odpowiedzi(Pytania pytania, String odpowiedz) {
       this.pytania = pytania;
       this.odpowiedz = odpowiedz;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Pytania getPytania() {
        return this.pytania;
    }
    
    public void setPytania(Pytania pytania) {
        this.pytania = pytania;
    }
    public String getOdpowiedz() {
        return this.odpowiedz;
    }
    
    public void setOdpowiedz(String odpowiedz) {
        this.odpowiedz = odpowiedz;
    }




}


