package com.Ankiety_PZ.hibernate;
// Generated 2020-04-16 17:33:57 by Hibernate Tools 4.3.1


import javax.persistence.CascadeType;
import javax.persistence.OneToMany;
import java.util.List;

/**
 * Odpowiedzi generated by hbm2java
 */
public class Odpowiedzi  implements java.io.Serializable {


     private Integer idOdpowiedzi;
     private Pytania pytania;
     private String odpowiedz;

    @OneToMany(mappedBy = "uzytkownicy",
            cascade = CascadeType.ALL,
            orphanRemoval = true)
    private List<OdpowiedziUzytkownicy> odpowiedziUzytkownicy;

    public Odpowiedzi(String s) {
    }

    public Odpowiedzi(Pytania pytania, String odpowiedz) {
       this.pytania = pytania;
       this.odpowiedz = odpowiedz;
    }
   
    public Integer getIdOdpowiedzi() {
        return this.idOdpowiedzi;
    }
    
    public void setIdOdpowiedzi(Integer id) {
        this.idOdpowiedzi = id;
    }
    public Pytania getPytania() {
        return this.pytania;
    }
    
    public void setPytania(Pytania pytania) {
        this.pytania = pytania;
    }
    public String getOdpowiedz() {
        return this.odpowiedz;
    }
    
    public void setOdpowiedz(String odpowiedz) {
        this.odpowiedz = odpowiedz;
    }




}


