package com.Ankiety_PZ.hibernate;
// Generated 2020-04-16 17:33:57 by Hibernate Tools 4.3.1


import javax.persistence.CascadeType;
import javax.persistence.OneToMany;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Pytania generated by hbm2java
 */
public class Pytania implements java.io.Serializable {


    private Integer idPytania;
    private Ankiety ankiety;
    private String tresc;
    private byte[] zdjecie;
    private Integer punktowe;
    private int rodzajPytania;
    private Set odpowiedzis;


    @OneToMany(mappedBy = "uzytkownicy",
            cascade = CascadeType.ALL,
            orphanRemoval = true)
    private List<PytaniaUzytkownicy> pytaniaUzytkownicy;


    public void initHashSetOdpowiedzi() {
        this.odpowiedzis = new HashSet<Odpowiedzi>();
    }


    public Pytania(Ankiety ankiety, String tresc, byte[] zdjecie, int rodzajPytania, Integer punktowe) {
        this.ankiety = ankiety;
        this.tresc = tresc;
        this.zdjecie = zdjecie;
        this.punktowe = punktowe;
        this.rodzajPytania = rodzajPytania;
    }

    public Pytania() {
    }

    public Pytania(Ankiety ankiety, String tresc, byte[] zdjecie, Integer punktowe, int rodzajPytania) {
        this.ankiety = ankiety;
        this.tresc = tresc;
        this.zdjecie = zdjecie;
        this.punktowe = punktowe;
        this.rodzajPytania = rodzajPytania;
        this.odpowiedzis = odpowiedzis;
    }

    public Integer getIdPytania() {
        return this.idPytania;
    }

    public void setIdPytania(Integer id) {
        this.idPytania = id;
    }

    public Ankiety getAnkiety() {
        return this.ankiety;
    }

    public void setAnkiety(Ankiety ankiety) {
        this.ankiety = ankiety;
    }

    public String getTresc() {
        return this.tresc;
    }

    public void setTresc(String tresc) {
        this.tresc = tresc;
    }

    public byte[] getZdjecie() {
        return this.zdjecie;
    }

    public void setZdjecie(byte[] zdjecie) {
        this.zdjecie = zdjecie;
    }

    public Integer getPunktowe() {
        return this.punktowe;
    }

    public void setPunktowe(Integer punktowe) {
        this.punktowe = punktowe;
    }

    public int getRodzajPytania() {
        return this.rodzajPytania;
    }

    public void setRodzajPytania(int rodzajPytania) {
        this.rodzajPytania = rodzajPytania;
    }

    public Set getOdpowiedzis() {
        return this.odpowiedzis;
    }

    public void setOdpowiedzis(Set odpowiedzis) {
        this.odpowiedzis = odpowiedzis;
    }

    public List<PytaniaUzytkownicy> getPytaniaUzytkownicy() {
        return pytaniaUzytkownicy;
    }

    public void setPytaniaUzytkownicy(List<PytaniaUzytkownicy> pytaniaUzytkownicy) {
        this.pytaniaUzytkownicy = pytaniaUzytkownicy;
    }

    public boolean isTheSame(Pytania pytania) {
        boolean result = false;
        if (idPytania.intValue() == pytania.getIdPytania().intValue()) {

            if (tresc.equals(pytania.tresc)) {

                if (rodzajPytania == pytania.getRodzajPytania()) {
                    result = true;
                }
            }
        }
        return result;
    }
}


